config/routes.rb
Rails.application.routes.draw do
  root 'homes#top'
  devise_for :users, controllers: {
    registrations: "users/registrations"
  }
  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end
  resources :users, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :validatable

  has_one_attached :avatar

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  VALID_PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]{6,128}\z/i
  validates :name, presence: true
  validates :email, presence: true, if: -> { errors_blank?(:email) }
  validates :email, format: { with: VALID_EMAIL_REGEX }, if: -> { errors_blank?(:email) }
  validates :password, presence: true, on: :create, if: -> { errors_blank?(:password) }
  validates :password, format: {
    with: VALID_PASSWORD_REGEX,
    message: "は半角英字・半角数字をそれぞれ1文字以上含む必要があります",
  }, allow_blank: true, if: -> {
                              errors_blank?(:password)
                            }

  def errors_blank?(attribute)
    errors[attribute].blank?
  end

  def self.guest
    find_or_create_by!(email: "guest@example.com") do |user|
      user.name = "ゲストユーザー"
      user.password = SecureRandom.urlsafe_base64
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!, except: [:top]
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :avatar])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :ensure_normal_user, only: [:edit, :update, :destroy]

  def ensure_normal_user
    if resource.email === "guest@example.com"
      redirect_back fallback_location: root_path, alert: "ゲストユーザーの更新・削除はできません。"
    end
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to root_path, notice: "ゲストユーザーとしてログインしました。"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/top.html.erb
<h1>Homes#top</h1>
<p>Find me in app/views/homes/top.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IdoTakeruPortfolio</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/f9f238d35a.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header>
      <% if user_signed_in? %>
        <%= render "layouts/shared/login_user_header" %>
      <% else %>
        <%= render "layouts/shared/no_login_user_header" %>
      <% end %>
      <%= render "layouts/shared/flash_message" %>
    </header>
    <%= yield %>
  </body>
</html>

app/views/layouts/shared/_flash_message.html.erb
<% if flash[:notice].present? %>
  <div class="container p-4 alert alert-success fade-in" id="flash-message">
    <%= notice %>
    <span class="close fa-solid fa-xmark fa-xl" style="cursor: pointer;"></span>
  </div>
<% end %>
<% if flash[:alert].present? %>
  <div class="container alert alert-warning fade-in" id="flash-message">
    <%= alert %>
    <span class="close fa-solid fa-xmark fa-xl" style="cursor: pointer;"></span>
  </div>
<% end %>

app/views/layouts/shared/_login_user_header.html.erb
<div class="px-3 py-2 bg-dark text-white">
  <div class="container">
    <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
      <%= link_to root_path, class: "d-flex align-items-center my-2 my-lg-0 me-lg-auto text-white text-decoration-none" do %>
      <dir style="height: 34px">
        <span class="bi me-2">
          <i class="fa-solid fa-house fa-2xl"></i>
        </span>
      </dir>
    <% end %>
        <ul class="nav col-12 col-lg-auto my-2 justify-content-center my-md-0 text-small">
          <li>
            <%= link_to user_path(current_user), class: "nav-link" do %>
              <% if current_user.avatar.attached? %>
                <%= image_tag current_user.avatar.variant(resize_to_limit: [50, 50]), class: "rounded-circle", alt: "ユーザーのアバター画像" if current_user.avatar.present? %>
              <% else%>
                <%= image_tag "default_image_user.jpg", size: "50x50", class: "rounded-circle", alt: "デフォルトのアバター画像" %>
              <% end %>
            <% end %>
          </li>
        </ul>
    </div>
  </div>
</div>
<div class="px-3 py-2 border-bottom mb-3">
  <div class="container d-flex flex-wrap justify-content-end">
    <div class="nav">
      <p><%= button_to "ログアウト", destroy_user_session_path, method: :delete, class: "btn btn-outline-danger" %></p>
    </div>
  </div>
</div>

app/views/layouts/shared/_no_login_user_header.html.erb
<div class="px-3 py-2 bg-dark">
  <div class="container">
    <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
      <%= link_to root_path, class: "d-flex align-items-center my-2 my-lg-0 me-lg-auto text-white text-decoration-none" do %>
        <dir style="height: 34px">
          <span class="bi me-2">
            <i class="fa-solid fa-house fa-2xl"></i>
          </span>
        </dir>
      <% end %>
      <ul class="nav col-12 col-lg-auto my-2 justify-content-center my-md-0 text-small">
        <li>
        </li>
      </ul>
    </div>
  </div>
</div>
<div class="px-3 py-2 border-bottom mb-3">
  <div class="container d-flex flex-wrap justify-content-end">
    <div class="nav">
        <%= link_to "ログイン", new_user_session_path, class: "btn btn-outline-primary me-2" %>
        <%= link_to "新規登録", new_user_registration_path, class: "btn btn-outline-secondary me-2" %>
        <%= button_to "ゲストログイン", users_guest_sign_in_path, method: :post, class: "btn btn-outline-info" %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <h1>Users#show</h1>
  <p><%= current_user.name %></p>
  <p><%= link_to "ユーザー情報変更", edit_user_registration_path %></p>
</div>